# Generated by Django 4.2.7 on 2026-01-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_cart_category_order_product_productimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
