# Generated by Django 4.2.7 on 2026-01-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='full_address',
        ),
    ]
