# Generated by Django 4.2.7 on 2026-01-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_full_name_address_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='productimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_image', to='store.productimage'),
        ),
    ]
